import React, { useState } from 'react';
import DayNightToggle from './components/DayNightToggle';

const App: React.FC = () => {
  const [isNight, setIsNight] = useState(false);

  const toggleTheme = () => {
    setIsNight(!isNight);
  };

  return (
    <div className={`min-h-screen w-full flex flex-col items-center transition-colors duration-700 py-12 px-4 gap-12 ${isNight ? 'bg-[#0f172a]' : 'bg-[#F0F4F8]'}`}>
      
      {/* Main Feature Panel */}
      <div className={`p-8 md:p-12 rounded-3xl shadow-xl flex flex-col items-center gap-8 border transition-colors duration-700 max-w-2xl w-full ${isNight ? 'bg-[#1e293b] border-[#334155]' : 'bg-white border-slate-100'}`}>
        <h1 className={`text-3xl font-bold tracking-tight transition-colors duration-700 ${isNight ? 'text-slate-100' : 'text-slate-800'}`}>
          {isNight ? 'Good Night' : 'Good Morning'}
        </h1>
        
        {/* Default Scale (1.0) */}
        <DayNightToggle isNight={isNight} onToggle={toggleTheme} scale={1} seed={1} />
        
        <p className={`font-medium text-sm tracking-wide transition-colors duration-700 ${isNight ? 'text-slate-400' : 'text-slate-400'}`}>
          Main Control
        </p>
      </div>

      {/* Grid for Sizes and Variations */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-8 w-full max-w-6xl items-start">
        
        {/* Scale Examples */}
        <div className={`p-8 rounded-2xl shadow-lg flex flex-col items-center gap-8 border transition-colors duration-700 h-full ${isNight ? 'bg-[#1e293b] border-[#334155]' : 'bg-white border-slate-100'}`}>
           <h2 className={`text-lg font-semibold ${isNight ? 'text-slate-200' : 'text-slate-700'}`}>Size Variations</h2>
           <div className="flex flex-col items-center justify-center gap-8 w-full">
               
               <div className="flex flex-col items-center gap-2">
                   <DayNightToggle isNight={isNight} onToggle={toggleTheme} scale={1.0} seed={1} />
                   <span className="text-xs text-slate-500 uppercase tracking-wider">1.0x (Original)</span>
               </div>
               
               <div className="flex flex-row flex-wrap items-end justify-center gap-8 w-full">
                  <div className="flex flex-col items-center gap-2">
                      <DayNightToggle isNight={isNight} onToggle={toggleTheme} scale={0.8} seed={1} />
                      <span className="text-xs text-slate-500 uppercase tracking-wider">0.8x</span>
                  </div>
                  <div className="flex flex-col items-center gap-2">
                      <DayNightToggle isNight={isNight} onToggle={toggleTheme} scale={0.6} seed={1} />
                      <span className="text-xs text-slate-500 uppercase tracking-wider">0.6x</span>
                  </div>
               </div>

               <div className="flex flex-row flex-wrap items-end justify-center gap-8 w-full">
                  <div className="flex flex-col items-center gap-2">
                      <DayNightToggle isNight={isNight} onToggle={toggleTheme} scale={0.4} seed={1} />
                      <span className="text-xs text-slate-500 uppercase tracking-wider">0.4x</span>
                  </div>
                  <div className="flex flex-col items-center gap-2">
                      <DayNightToggle isNight={isNight} onToggle={toggleTheme} scale={0.25} seed={1} />
                      <span className="text-xs text-slate-500 uppercase tracking-wider">0.25x</span>
                  </div>
               </div>

           </div>
        </div>

        {/* Seed/Randomness Examples (Fixed Scale 0.6) */}
        <div className={`p-8 rounded-2xl shadow-lg flex flex-col items-center gap-8 border transition-colors duration-700 h-full ${isNight ? 'bg-[#1e293b] border-[#334155]' : 'bg-white border-slate-100'}`}>
           <h2 className={`text-lg font-semibold ${isNight ? 'text-slate-200' : 'text-slate-700'}`}>Star Seeds (0.6x)</h2>
           <p className={`text-sm text-center -mt-4 mb-2 ${isNight ? 'text-slate-400' : 'text-slate-500'}`}>
             Switch to Night mode to see different star patterns generated by seeds.
           </p>
           <div className="flex flex-col items-center gap-8">
               <div className="flex flex-col items-center gap-2">
                   <DayNightToggle isNight={isNight} onToggle={toggleTheme} scale={0.6} seed={123} />
                   <span className="text-xs text-slate-500 uppercase tracking-wider">Seed 123</span>
               </div>
               <div className="flex flex-col items-center gap-2">
                   <DayNightToggle isNight={isNight} onToggle={toggleTheme} scale={0.6} seed={999} />
                   <span className="text-xs text-slate-500 uppercase tracking-wider">Seed 999</span>
               </div>
               <div className="flex flex-col items-center gap-2">
                   <DayNightToggle isNight={isNight} onToggle={toggleTheme} scale={0.6} seed={42} />
                   <span className="text-xs text-slate-500 uppercase tracking-wider">Seed 42</span>
               </div>
           </div>
        </div>

      </div>
    </div>
  );
};

export default App;